import torch
import torch.nn.functional as F
from transformers import AutoTokenizer, AutoModel
from sentence_transformers import SentenceTransformer

def main():
    """
    Compares embeddings generated by two different implementations
    of the same pretrained language model.

    The function generates embeddings for a small set of sample texts
    using both the SentenceTransformer library and the Transformers
    library. It then compares the resulting embeddings to determine
    how closely the two approaches match.

    The comparison helps verify that the custom Transformers
    implementation produces results consistent with the
    SentenceTransformer implementation.

    Args:
        None

    Returns:
        None
    """

    MODEL_NAME = "sentence-transformers/all-mpnet-base-v2"

    texts = [
        "This is a test article about technology and artificial intelligence.",
        "The weather is expected to remain sunny throughout the weekend.",
    ]


    # --------------------------------------------------
    # SentenceTransformer implementation
    # --------------------------------------------------

    print("Loading SentenceTransformer...")

    # Load the pretrained model used to convert text into numerical
    # representations of its meaning.
    sentence_model = SentenceTransformer(
        MODEL_NAME,
        model_kwargs={"torch_dtype": torch.float16}
    )

    # Generate one numerical representation for each text.
    st_embeddings = sentence_model.encode(
        texts,
        show_progress_bar=False
    )

    print("SentenceTransformer embeddings:")
    print(st_embeddings.shape)


    # --------------------------------------------------
    # Transformers implementation
    # --------------------------------------------------

    # Load the tools needed to prepare the text for the model.
    print("\nLoading Transformers model...")

    # Load the tokenizer used to prepare the text for the model.
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)

    # Load the same pretrained model using the Transformers library.
    transformer_model = AutoModel.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.float16
    )

    # Put the model into evaluation mode because it is only being used
    # to generate embeddings, not to learn from new data.
    transformer_model.eval()

    # Convert the text into a format that the model can process.
    # Padding makes the texts the same length, while truncation prevents
    # texts from becoming longer than the model can handle.
    inputs = tokenizer(
        texts,
        padding=True,
        truncation=True,
        return_tensors="pt"
    )

    # Generate the model's representation of each text without
    # performing any training or changing the model.
    with torch.no_grad():
        outputs = transformer_model(**inputs)

    # Get the numerical representation produced for every word or
    # piece of a word in each text.
    token_embeddings = outputs.last_hidden_state

    # Identify which parts of the input contain actual text and
    # which parts were added only to make the texts the same length.
    attention_mask = inputs["attention_mask"]

    # Use the mask to ignore the extra padding when combining
    # the representations of the individual words or word pieces.
    mask = attention_mask.unsqueeze(-1).expand(token_embeddings.size()).float()

    # Add together the representations of the actual words or
    # word pieces in each text.
    sum_embeddings = torch.sum(token_embeddings * mask, dim=1)

    # Count the number of actual words or word pieces in each text.
    # The minimum value prevents an error if no text is present.
    sum_mask = torch.clamp(mask.sum(dim=1), min=1e-9)

    # Calculate the average representation of each text.
    mean_embeddings = sum_embeddings / sum_mask

    # Scale the resulting representations so they can be compared
    # consistently with the SentenceTransformer results.
    transformer_embeddings = F.normalize(
        mean_embeddings,
        p=2,
        dim=1
    )

    # Convert the results into a NumPy array for comparison.
    transformer_embeddings = transformer_embeddings.cpu().numpy()

    print("Transformers embeddings:")
    print(transformer_embeddings.shape)


    # --------------------------------------------------
    # Compare
    # --------------------------------------------------

    # Calculate the difference between the two sets of results.
    # Smaller differences mean the two implementations are producing
    # more similar representations.
    difference = abs(st_embeddings - transformer_embeddings)

    # Find the largest difference between any two values.
    print("\nMaximum absolute difference:")
    print(difference.max())

    # Find the average difference across all values.
    print("\nMean absolute difference:")
    print(difference.mean())

if __name__ == "__main__":
    main()